In [ ]:
# homework 6

In [2]:
import numpy as np

In [ ]:
######3.1- 1D NumPy Arrays

In [2]:
list = [20,27,9,12,31,17,4,50,39,35]

arr = np.array(list)

In [16]:
print(arr*4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(arr[6])
print(arr[7])
print(np.min(arr))
print(np.max(arr))

boolean_indexing = arr > 20
arr2= arr[boolean_indexing]
print(arr2)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50
4
50
[27 31 50 39 35]


In [58]:
######3.2 2D NumPy Arrays

In [19]:
matrix = np.array([
    [5, 12, 17, 9],
    [8,21,14,3],
    [6, 13, 19, 11]
])

In [23]:
np.shape(matrix)
#There are 3 rows and 4 columns in the array

(3, 4)

In [37]:
print(matrix[:,2])
print(matrix[1])
print(matrix *2)

print(np.mean(matrix[:,0]))
print(np.mean(matrix[:,1]))
print(np.mean(matrix[:,2]))
print(np.mean(matrix[:,3]))

print(np.mean(matrix))

print(np.max(matrix[0]))
print(np.max(matrix[1]))
print(np.max(matrix[2]))

print(np.min(matrix[:,0]))
print(np.min(matrix[:,1]))
print(np.min(matrix[:,2]))
print(np.min(matrix[:,3]))


[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
6.333333333333333
15.333333333333334
16.666666666666668
7.666666666666667
11.5
17
21
19
5
12
14
3


In [39]:
matrix.flatten()
#The array now only has one column. It was turned into a one dimensional array by putting all the numbers in the same row. 

array([ 5, 12, 17,  9,  8, 21, 14,  3,  6, 13, 19, 11])

In [57]:
print(np.argmin(matrix))
print(np.argmax(matrix))

print(np.unravel_index([7,5], (3,4)))


7
5
(array([1, 1]), array([3, 1]))


In [60]:
moreboolean_indexing = matrix > 15
matrix2 = matrix[moreboolean_indexing]
print(matrix2)

[17 21 19]


In [67]:
#I did this for both arrays, since I'm not sure which is being reffered to. 

print(np.sort(matrix, axis = 1))

print(np.sort(matrix2, axis = None))


[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]
[17 19 21]


In [3]:
#####4- Prime Star Systems

arr = np.array([
    [2,3,5],
    [14,6,8],
    [11, 13, 17],
    [7,10,13]
])

def checkprime(num): 
    if num < 2:
        return False
    for i in range(2, int(num**0.5)+1):
        if num % i == 0:
            return False
    return True

def primenum_rows(arr):
    new_arr = []
    for row in arr:
        if any(checkprime(num) for num in row):
                new_arr.append(row)
    return np.array(new_arr)

print(primenum_rows(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [112]:
#####5- Let's Play Checkers
def original_checkerboard(x,y): 
    return np.zeros(shape = (x,y))

print(original_checkerboard(8,8))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [126]:
#combined 5.2 and 5.3 here! hope that's ok

def checkerboard(): 
    checkerboard = original_checkerboard(8,8)
    for row in range(0,8):
        if row % 2 == 0:
            for i in range(0,7,2):
                checkerboard[row][i] = 1
        elif row % 2 == 1:
            for i in range(1,7,2):
                checkerboard[row][i] = 1
    return checkerboard
                
checkerboard()

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.]])

In [127]:
def reverse_checkerboard():
    checkerboard = original_checkerboard(8,8)
    for row in range(0,8):
        if row % 2 == 1:
            for i in range(0,7,2):
                checkerboard[row][i] = 1
        elif row % 2 == 0:
            for i in range(1,7,2):
                checkerboard[row][i] = 1
    return checkerboard

reverse_checkerboard()

array([[0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
######6- Expanding Universe

In [234]:
#inputting an array of strings and an intenger, return the strings with intenger-specified number of spaces between the letters
def expansion(arr, intenger):
    number_of_spaces= []
    empty_list= []
    for i in range(1,intenger):
        number_of_spaces.append(' ')
    number_of_spaces_but_a_string = ''.join(number_of_spaces)
    for string in arr:
        char_list = list(string)
        new_list = []
        for letter in char_list[:-1]:
            new_list.append(letter + number_of_spaces_but_a_string)
        new_list.append(char_list[-1])
        final_string= ''.join(new_list)
        empty_list.append(final_string) 
    final_array = np.array(empty_list)
    print(final_array)
            
arr= np.array(["galaxy", "clusters"])
expansion(arr,5)


['g    a    l    a    x    y' 'c    l    u    s    t    e    r    s']


In [ ]:
#######7 - Second Brightest Star

In [239]:
def secondBrightest(array):
    empty_list = []
    for row in array:
        brightest = row[0]
        second_brightest = row[0]
        for number in row:
            if number > brightest:
                brightest = number
        for number in row:
            if number < brightest and number> second_brightest:
                second_brightest = number
        empty_list.append(second_brightest)
    final_array = np.array(empty_list)
    print(final_array)
                
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)


secondBrightest(stars)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
